# -*- coding: utf-8 -*-
"""StudentPerformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwZ6gFhinVlkY7uYn32dU3zcg53pX0LN
"""

import pandas as pd
df = pd.read_csv('enhanced_student_habits_performance_dataset.csv')
df.head()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sb

"""## 0. Data Preprocessing"""

print(df.info())
print(df.describe())

df.columns

df['exam_score'].mean() # 89

"""## 1. Pattern Analysis based on  Major"""

df['major'].unique()

grouped = df.groupby('major')['study_hours_per_day'].mean()
plt.figure(figsize=(11,5))
plt.bar(df['major'].unique(), grouped, color = 'skyblue')
plt.title('Average Study Hours per Major')
plt.xlabel('major')
plt.ylabel('avg study hours')
plt.show()

# Business major students studies the most hours !!
# Let's see what their lifestyle looks like

grouped_anxiety = df.groupby('major')['exam_anxiety_score'].mean()

plt.figure(figsize=(11,5))
plt.bar(df['major'].unique(), grouped_anxiety, color = 'skyblue')
plt.title('Average Exam Anxiety Score per Major')
plt.xlabel('major')
plt.ylabel('exam anxiety score')
plt.show()

"""### Family support level per major

"""

parent_support = df.groupby('major')['parental_support_level'].mean()


plt.figure(figsize=(11,5))
plt.bar(df['major'].unique(), parent_support, color = 'skyblue')
# plt.title('Average Exam Anxiety Score per Major')
plt.xlabel('major')
plt.ylabel('exam anxiety score')
plt.show()

df['family_income_range'].unique()

income_map = {'Low': 1, 'Medium': 2, 'High': 3}
df['income_level_num'] = df['family_income_range'].map(income_map)

df['income_level_num'].head(6)

major_income = df.groupby('major')['income_level_num'].mean()
major_income

plt.bar(major_income.index, major_income.values)
plt.show()
# almost the same

df['parental_education_level'].unique()

"""exam score <-> parents' education level"""

# income_map = {'Low': 1, 'Medium': 2, 'High': 3}
# df['income_level_num'] = df['family_income_range'].map(income_map)

edu_map = {'High School' : 1, 'Some College' : 2, 'Bachelor' : 3, 'Master' : 4, 'PhD' : 5}
df['parental_education_level_num'] = df['parental_education_level'].map(edu_map)
# df['parental_education_level_num'].head()

avg_scores = df.groupby('parental_education_level')['exam_score'].mean().sort_values()

plt.figure(figsize=(10, 6))
plt.bar(avg_scores.index, avg_scores.values, color='skyblue')
plt.show()

df['exam_score'].mean()

"""# 2. Correlatoin"""

df_str = df.select_dtypes(include = 'object')
df_str

# numeric data only
df_corr = df.select_dtypes(include=['integer','float'])
df_corr = df_corr.drop('student_id',axis=1)
df_corr

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

corr = df_corr.corr()

plt.figure(figsize=(17,17))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix (Numeric columns only)')
plt.show()

import numpy as np

corr = df.select_dtypes(include=['float','int']).corr().abs()
upper = corr.where(~np.tril(np.ones(corr.shape)).astype(bool))
top_n = upper.stack().sort_values(ascending=False).head(15)

print(top_n)

target_vars = ['previous_gpa', 'exam_score']
corr_vals = corr[target_vars].drop(index=target_vars).sort_values(by = 'exam_score', ascending = False)


corr_vals.plot(kind='bar', figsize=(10, 6))
plt.title('Correlation with previous_gpa and exam_score')
plt.ylabel('Correlation Coefficient')
# plt.xticks(rotation = 45)
plt.grid(True, alpha = 0.3)
plt.tight_layout()
plt.show()

# Key factors that affect exam score are motivation level, study hours per day, exam anxiety score, screen time, stress level, sleep hours and exercise frequency.
# Let's build a predict model that estimate one's final exam score based on above 7 key factors that determine academic score(gpa).

# prediction model based on students' life behavior effecting to exam score

df.groupby('dropout_risk')['exam_score'].mean()

df.groupby('access_to_tutoring')['exam_score'].mean()

# Quiet Room > Library > Co-Learning Group > Cafe > Dorm
df.groupby('study_environment')['exam_score'].mean()

"""### Bonus. Unrelated two factors"""

df.groupby('gender')['exam_score'].mean()

df.groupby('learning_style')['exam_score'].mean()

df.groupby('learning_style')['exam_score'].mean()

df.groupby('family_income_range')['exam_score'].mean()

df.groupby('diet_quality')['exam_score'].mean()

df.groupby('family_income_range')['exam_score'].mean()

# Parental education level does not effect to students' exam score
df.groupby('parental_education_level')['exam_score'].mean()

df.groupby('part_time_job')['attendance_percentage'].mean()

df.groupby('part_time_job')['study_hours_per_day'].mean()

df.groupby('part_time_job')['exam_score'].mean()

"""People might easily assume having a part time job will let student study less, but it's not the case. Either their score or study hours are telling that there is no big difference.
Also based on my personal experience, "PART" time job let me to experience diversed world (and enriched my taste for coffee :D). I would definitely recommend any college student to have a part time job. Won't ruin your finals.
"""

df.groupby('extracurricular_participation')['exam_score'].mean()

df.groupby('internet_quality')['exam_score'].mean()



"""# 3. Predict Model"""

# [Recap] Insight based on Correlation Analysis

# Key factors that affect exam score are motivation level, study hours per day, exam anxiety score, screen time, stress level, sleep hours and exercise frequency.
# Let's build a predict model that estimate one's final exam score based on above 7 key factors that determine academic score(gpa).

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X = df[['motivation_level','study_hours_per_day','exam_anxiety_score','screen_time','stress_level','sleep_hours','exercise_frequency']]
y = df['exam_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

import numpy as np
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE: {rmse:.2f}")  # 예: 10.73 정도

"""## 2nd model"""



X = df[['study_hours_per_day']]
y = df['exam_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

import numpy as np
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE: {rmse:.2f}")  # 예: 10.73 정도

"""## 3rd model"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np


X = df[['motivation_level','study_hours_per_day','exam_anxiety_score','screen_time','stress_level','sleep_hours','exercise_frequency']]
y = df['exam_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the Model
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluation
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f"MSE: {mse:.2f}, RMSE: {rmse:.2f}")

# Basically, Pearson Correlation was at most 0.25, so these prediction based on this data will not represent or predict the exam score.
# Instead of predicting the general score, but let's dive into study lifestyle of high score classes.

"""# 4. Prediction Model"""

import pandas as pd
df = pd.read_csv('enhanced_student_habits_performance_dataset.csv')
df.head()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sb

cat_cols = df.select_dtypes(include='object').columns # columns indecies

print(cat_cols) # index of columns which are object types

df_encoded = pd.get_dummies(df, columns=cat_cols,dtype=int,drop_first=True)

df_encoded.head()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = df_encoded.drop('exam_score', axis=1)
y = df_encoded['exam_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)

print("Test Accuracy:", model.score(X_test, y_test))



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

corr = df_encoded.corr()

plt.figure(figsize=(30,30))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix (Numeric columns only)')
plt.show()

corr = df.select_dtypes(include=['float','int']).corr().abs()
upper = corr.where(~np.tril(np.ones(corr.shape)).astype(bool))
top_corr = upper.stack().sort_values(ascending=False).head(15)

# top 15 indicides have high correlation
top_corr

